### ISSUE TITLE
ValueError: Loss is nan.

### ISSUE THREAD

**Issue by Q-Z-Y** [alokwhitewolf/Guided-Attention-Inference-Network#4]
Thank you for sharing the implementation. I tried to reproduce by running 'train_classifier.py' which produces classifier_model_14640, then running train_GAIN.py with the classifier_model_14640 as the pretrained FCN8 model. However it throw out this error 'ValueError: Loss is nan.' at [line 206, fcn8.py]. All variables after conv2 seem to be all nan. Please could you have a look at this problem? Many thanks.

**Comment by alokwhitewolf** [comment]
Hello. Thanks for opening the issue. 
I tried to replicate but was unable to. I faced no problems as such.
Out of curiosity,  did you run train_GAIN by using GPU or CPU ?

**Comment by Qiang-Zhang-Y** [comment]
It ran on GPU with Anaconda on windows 10, package list:
```
Package         Version
--------------- ----------
certifi         2018.10.15
chainer         4.5.0
chainercv       0.10.0
chardet         3.0.4
cloudpickle     0.6.1
cupy-cuda80     4.5.0
cycler          0.10.0
dask            0.19.4
decorator       4.3.0
fastrlock       0.4
fcn             6.4.7
filelock        3.0.9
gdown           3.5.0
idna            2.7
kiwisolver      1.0.1
matplotlib      3.0.0
networkx        2.2
numpy           1.15.2
pandas          0.23.4
Pillow          5.3.0
pip             18.1
protobuf        3.6.1
pyparsing       2.2.2
python-dateutil 2.7.3
pytz            2018.5
PyWavelets      1.0.1
PyYAML          3.13
requests        2.19.1
scikit-image    0.14.1
scikit-learn    0.20.0
scipy           1.1.0
setuptools      40.4.3
six             1.11.0
toolz           0.9.0
tqdm            4.27.0
urllib3         1.23
wheel           0.32.1
wincertstore    0.2
```
 and the error msg is as follows when running 
`python train_GAIN.py --modelfile "result/classifier_model_58560" --device 0
`
```
total [#.................................................]  3.00%
this epoch [####################..............................] 40.98%
       600 iter, 0 epoch / 20000 iterations
     2.508 iters/sec. Estimated time to finish: 2:08:55.318948.
Exception in main training loop: Loss is nan.
Traceback (most recent call last):
  File "C:\Users\user1\Anaconda3\envs\Chainer\lib\site-packages\chainer\training\trainer.py", line 316, in run
    update()
  File "C:\Users\user1\Anaconda3\envs\Chainer\lib\site-packages\chainer\training\updaters\standard_updater.py", line 149, in update
    self.update_core()
  File "C:\Users\user1\Documents\Guided-Attention-Inference-Network-master\updater.py", line 80, in update_core
    segment_loss = self._optimizers['main'].target(image, labels)
  File "C:\Users\user1\Documents\Guided-Attention-Inference-Network-master\models\fcn8.py", line 252, in __call__
    return self.segment(x, t)
  File "C:\Users\user1\Documents\Guided-Attention-Inference-Network-master\models\fcn8.py", line 206, in segment
    raise ValueError('Loss is nan.')
Will finalize trainer extensions and updater before reraising the exception.

Process finished with exit code -1
```

Loss was reducing but went to nan suddenly.
![total_loss](https://user-images.githubusercontent.com/19362216/47114524-f76c7980-d253-11e8-9da5-e3f4f38ec507.png)

Any suggestion would be appreciated.
Thanks

**Comment by mongoose54** [comment]
@Q-Z-Y cc-ing @alokwhitewolf 

It happens to me too. The reason is that the attention maps is zero for the ground truth when using the trained classifier. I noticed that the longer you train the classifier (`train_classifier.py`) the less chance you are getting of NaN
